services:
  jira-cluster-db:
    platform: ${JIRA_PLATFORM}
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: jira-cluster-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=test-123
      - MSSQL_PID=Developer
    networks:
      jira-cluster-network:
        aliases:
          - jira-cluster-db
  jira-cluster-lb:
    platform: ${JIRA_PLATFORM}
    image: codeclou/docker-atlassian-jira-data-center:loadbalancer-9837a52
    container_name: jira-cluster-lb
    links:
      - jira-cluster-node1
    ports:
      - "18134:18134"
    environment:
      - LB_PORT=18134
      - NODES=2
      - NODES_NAME_SCHEMA=jira-cluster-node___NUM___
    volumes:
      - /Users/dagrato/jira-dc/jira-cluster/:/opt/
    networks:
      jira-cluster-network:
        aliases:
          - jira-cluster-lb
  jira-cluster-node1:
    platform: ${JIRA_PLATFORM}
    image: ${JIRA_IMAGE}
    container_name: jira-cluster-node1
    links:
      - jira-cluster-db
    environment:
      # Memory / Heap Size
      - JVM_MAXIMUM_MEMORY=4096M
      - JVM_MAXIMUM_MEMORY=8192M
      # Reverse Proxy Settings
      - ATL_PROXY_NAME=jira-cluster-lb
      - ATL_PROXY_PORT=18134
      # Database
      - ATL_JDBC_URL=jdbc:sqlserver://jira-cluster-db:1433;database=jira
      - ATL_JDBC_USER=sa
      - ATL_JDBC_PASSWORD=test-123
      - ATL_DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - ATL_DB_TYPE=mssql
      # Data Center configuration
      - CLUSTERED=true
      - JIRA_NODE_ID=jira-cluster-node1
      - EHCACHE_LISTENER_HOSTNAME=jira-cluster-node1
      - EHCACHE_LISTENER_PORT=40001
      - EHCACHE_OBJECT_PORT=40011
      - EHCACHE_PEER_DISCOVERY=default
      # Home Directories
      - JIRA_HOME=/opt/jira-home
      - JIRA_SHARED_HOME=/opt/jira-home-shared
    volumes:
      - type: bind
        source: /Users/dagrato/jira-dc/jira-cluster/jira-home-node1
        target: /opt/jira-home
      - type: bind
        source: /Users/dagrato/jira-dc/jira-cluster/jira-home-shared
        target: /opt/jira-home-shared
    depends_on:
      - jira-cluster-db
    networks:
      jira-cluster-network:
        aliases:
          - jira-cluster-node1
  jira-cluster-node2:
    platform: ${JIRA_PLATFORM}
    image: ${JIRA_IMAGE}
    container_name: jira-cluster-node2
    links:
      - jira-cluster-db
    environment:
      # Memory / Heap Size
      - JVM_MAXIMUM_MEMORY=4096M
      - JVM_MAXIMUM_MEMORY=8192M
      # Reverse Proxy Settings
      - ATL_PROXY_NAME=jira-cluster-lb
      - ATL_PROXY_PORT=18134
      # Database
      - ATL_JDBC_URL=jdbc:sqlserver://jira-cluster-db:1433;database=jira
      - ATL_JDBC_USER=sa
      - ATL_JDBC_PASSWORD=test-123
      - ATL_DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - ATL_DB_TYPE=mssql
      # Data Center configuration
      - CLUSTERED=true
      - JIRA_NODE_ID=jira-cluster-node1
      - EHCACHE_LISTENER_HOSTNAME=jira-cluster-node1
      - EHCACHE_LISTENER_PORT=40001
      - EHCACHE_OBJECT_PORT=40011
      - EHCACHE_PEER_DISCOVERY=default
      # Home Directories
      - JIRA_HOME=/opt/jira-home
      - JIRA_SHARED_HOME=/opt/jira-home-shared
    volumes:
      - type: bind
        source: /Users/dagrato/jira-dc/jira-cluster/jira-home-node1
        target: /opt/jira-home
      - type: bind
        source: /Users/dagrato/jira-dc/jira-cluster/jira-home-shared
        target: /opt/jira-home-shared
    depends_on:
      - jira-cluster-db
    networks:
      jira-cluster-network:
        aliases:
          - jira-cluster-node2
volumes:
  jira-cluster:
networks:
  jira-cluster-network:
    driver: bridge